#!/bin/sh

# TODO: Fold this functionality into bean-machine itself, under a `repair`
# or `delint` command.

echo "Removing .AppleFileInfo:"
find ~/muzak -name .AppleFileInfo -print0 | xargs -0 rm -rf

echo "Removing .DS_Store:"
find ~/muzak -name .DS_Store -print0 | xargs -0 rm

echo "Showing hidden files and directories:"
find ~/muzak -name '.*'

echo "Deleting empty directories:"
find ~/muzak -type d -print0 | xargs -0 rmdir 2> /dev/null

echo "Setting permissions:"
find ~/muzak -type f -print0 | xargs -0 chmod 644
find ~/muzak -type d -print0 | xargs -0 chmod 755

echo "Clearing xattrs:"
find ~/muzak -type f -print0 | xargs -0 xattr clear

# TODO:
# if 1 jpg and not named cover.jpg, change it
# search for files not named *.mp3, *.jpg
